// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDynvZ1oeETN7NjAmg_X06QasEVYAvNox0',
    appId: '1:106864347153:web:87e10df16c05e71784c9b0',
    messagingSenderId: '106864347153',
    projectId: 'wakenya-insurance',
    authDomain: 'wakenya-insurance.firebaseapp.com',
    storageBucket: 'wakenya-insurance.firebasestorage.app',
    measurementId: 'G-K21LTNY8J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAscKLP5S3-4fykMnMjwXFdat4Og-GDt-w',
    appId: '1:106864347153:android:192fd58ffa6bb1d584c9b0',
    messagingSenderId: '106864347153',
    projectId: 'wakenya-insurance',
    storageBucket: 'wakenya-insurance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzod52igpuYJi1mciEKx5lL5zHn0HF6Qw',
    appId: '1:106864347153:ios:d1cca0eb94f7bb5a84c9b0',
    messagingSenderId: '106864347153',
    projectId: 'wakenya-insurance',
    storageBucket: 'wakenya-insurance.firebasestorage.app',
    iosBundleId: 'com.example.wakenyaTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzod52igpuYJi1mciEKx5lL5zHn0HF6Qw',
    appId: '1:106864347153:ios:d1cca0eb94f7bb5a84c9b0',
    messagingSenderId: '106864347153',
    projectId: 'wakenya-insurance',
    storageBucket: 'wakenya-insurance.firebasestorage.app',
    iosBundleId: 'com.example.wakenyaTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDynvZ1oeETN7NjAmg_X06QasEVYAvNox0',
    appId: '1:106864347153:web:ef562d9421fa413384c9b0',
    messagingSenderId: '106864347153',
    projectId: 'wakenya-insurance',
    authDomain: 'wakenya-insurance.firebaseapp.com',
    storageBucket: 'wakenya-insurance.firebasestorage.app',
    measurementId: 'G-ZB7F35QBXV',
  );
}
