/ File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUH-R2wRP634QPCsZDrO-ftIMw-teGq74',
    appId: '1:772666698917:web:c9c4135dc8e5a6deb5b14c',
    messagingSenderId: '772666698917',
    projectId: 'summit-university',
    authDomain: 'summit-university.firebaseapp.com',
    storageBucket: 'summit-university.firebasestorage.app',
    measurementId: 'G-D6FXFP9STL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIN4BOH84SORiG3N-AIzs2V_z4fY9CFuo',
    appId: '1:772666698917:android:aa43b7fa0091d625b5b14c',
    messagingSenderId: '772666698917',
    projectId: 'summit-university',
    storageBucket: 'summit-university.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA088ATYZaLIJ73xfO36l98noYEOXk_Al0',
    appId: '1:772666698917:ios:fb6afb4af6a48c3fb5b14c',
    messagingSenderId: '772666698917',
    projectId: 'summit-university',
    storageBucket: 'summit-university.firebasestorage.app',
    iosBundleId: 'com.example.untitled9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA088ATYZaLIJ73xfO36l98noYEOXk_Al0',
    appId: '1:772666698917:ios:fb6afb4af6a48c3fb5b14c',
    messagingSenderId: '772666698917',
    projectId: 'summit-university',
    storageBucket: 'summit-university.firebasestorage.app',
    iosBundleId: 'com.example.untitled9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUH-R2wRP634QPCsZDrO-ftIMw-teGq74',
    appId: '1:772666698917:web:2d16475818943ac6b5b14c',
    messagingSenderId: '772666698917',
    projectId: 'summit-university',
    authDomain: 'summit-university.firebaseapp.com',
    storageBucket: 'summit-university.firebasestorage.app',
    measurementId: 'G-S7V0SSHMC1',
  );
}
